---
title: "Data analysis"
output: pdf_document
---
```{r}
library(vegan)
library(betapart)
library(grid)
library(ggplot2)
library(adespatial)
library(fossil)
```
NDMS with variable surfing
```{r}

getwd()
species = read.csv("input_data.csv")
#-----------------------------------------------------alternative
species<-read.table("clipboard", header=T, sep="\t")
enviro<-read.table("clipboard", header=T, sep="\t")

species <- species[-c(86), ] ; enviro <- enviro[-c(86), ]

species_NMDS <- species[,6:760] ; rownames(species_NMDS) <- paste(species$river, species$sampleID,sep=" ")
enviro_NMDS <- enviro[,6:15] ; rownames(enviro_NMDS) <- paste(enviro$river, enviro$sampleID,sep=" ")

example_NMDS=metaMDS(species_NMDS,k=3) #k=2dimesnions amnd trymax=max number of random starts in                                                        search of stable solution (makes the iterations a bit                                                            longer)
example_NMDS

scrs <- as.data.frame(scores(example_NMDS, display = "sites"))
vf <- envfit(example_NMDS, enviro_NMDS, perm = 999,na.rm=T, choices=c(1,2))
#fit environemntal variables to NMDS ('envfit' works the other direction to RDA, 
#how ordination explains enviro variation; run RDA if you want to compare
#geo vs. enviro or how well enviro predicts species)

spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, shape = species$river),size=4) +
  scale_shape_manual(values=c(0,15,1,19,2,17,8,18,6,7)) +
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = spp.scrs,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = spp.scrs, aes(x = NMDS1, y = NMDS2, label = Species),
            size = 3)

ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, shape = species$zone),size=4) +
  scale_shape_manual(values=c(0,15,1,19,2,17,8,18,6,7)) 
  
ggplot() +
  geom_text(data = scrs, aes(x = NMDS1, y = NMDS2, label = rownames(scrs)),
            size = 3)
  

#basic plots for NMDS
ordisurf(example_NMDS,species$tn,main="",col="forestgreen")
orditorp(example_NMDS,display="sites",col="grey30",air=0.1,cex=1)


#inference
anosim(species_NMDS, species$river, permutations=999)
stressplot(example_NMDS)

```

Alpha and beta diversity
```{r}
#Diversity metrics--------------------------------------------------------------------------------------
library(vegan)
library(betapart)
#shanon diversity
spec <- species[,6:760]
shannon<-diversity(spec, index = "shannon")
shannon<-as.vector(shannon)
shannon<-as.data.frame(shannon)

plot(shannon)
diversity<-cbind(shannon,species[,1:6])
plot(diversity$river,diversity$shannon)
write.csv(diversity,file = "C:/Users/admin/Dropbox/b.mscripts/biofilmMARC/Datasets/working datasets/diversity.csv")

#for betadiversity-------with pres/absence data
presabs<-ifelse(spec>0,1,0)
dist<-beta.pair(presabs, index.family="sorensen")
# To get the pairwise Jaccard index turnover partition between communities, type: dist[[1]]. 
#To get nestedness partition, type: dist[[2]]. To get all beta diversity: dist[[3]].
dist[[2]]
# If we want to compare the beta diversities of communities aggregated by groups
#we can use "betadisper" analysis.
#=======
groups <- factor(species$river)
#=======
groups <- factor(species$region)
#=======
bd<-betadisper(dist[[3]],groups)
plot(bd)
boxplot(bd)
anova(bd)
```

```{r}
# Using bray-curtis dissimilarity and thus abundance data as well
#The function will calculate beta diversity (and its partitions) based on Bray-Curtis dissimilarity index.
spec<-read.table("clipboard",header=T,sep="\t")
dist<-beta.pair.abund(spec, index.family = "bray")
turnover<-as.data.frame(as.vector(dist$beta.bray.bal))
nestedness<-as.data.frame(as.vector(dist$beta.bray.gra))
beta<-as.data.frame(as.vector(dist$beta.bray))
beta<-cbind(turnover,nestedness,beta)
write.csv(beta,file = "C:/Users/mpeipoch/Dropbox/b_manuscritpts/biofilmMARC/Datasets/working datasets/beta.csv")


#compare to geographic distance
presabs<-ifelse(spec>0,1,0) #using pres/abs data and sorensen index Baselga 2012
dist<-beta.pair(presabs, index.family="sorensen")
turnover<-as.data.frame(as.vector(dist[[1]]))
nestedness<-as.data.frame(as.vector(dist[[2]]))
beta<-as.data.frame(as.vector(dist[[3]]))

geo<-read.table("clipboard",header=T,sep="\t")
geographic<-as.data.frame(as.vector(earth.dist(geo,dist = T)))
reg<-lm(nestedness[,1] ~ geographic[,1])
summary(reg)

```

try beta.div() to get SCBD and LCBD
```{r}
spec<-subset(species, river=="Tongue")
spec<-spec[,6:760]
bd<-beta.div(spec, method="hellinger")
bd<-as.data.frame(bd$SCBD)
SCbd<-cbind(SCbd,bd)
write.csv(SCbd,file = "C:/Users/mpeipoch/Dropbox/b_manuscritpts/biofilmMARC/Datasets/working datasets/beta.csv")
```

fast plot on node degree vs. closness centrality with %OC---to identify keystone taxa
```{r}
network_data<-read.table("clipboard",header=T,sep="\t")
SCBD<-read.table("clipboard",header=T,sep="\t")
merged_data<-merge(network_data,SCBD, by="id")
ggplot(merged_data, aes(x=att4, y=Degree, colour=log(scbd+1))) + geom_point() + 
  scale_colour_gradientn(colours=rainbow(4)) 
```

```{r}
data<-read.table("clipboard",header=T,sep="\t")
ggplot(data, aes(x=x, y=y, size=z2)) + geom_point()  
  

```

