---
title: "networks"
output: html_document
---
Necessary packages
```{r}
#necessary packages:
library("data.table")
library("dplyr")
library("igraph")
library("stringi")
library("Hmisc")
library("rgexf")
library("sm")
```

Data input
```{r}
#intro OTU table: all numeric, OTUnames as columns
getwd() 
data = read.csv("genus_rarefied.csv")
```

Alternative data input
```{r}
data <-read.table("clipboard", header = T, sep = "\t")
attributes <-read.table("clipboard", header = T, sep = "\t")#ONLY in case need to copy/paste dataset in
```

Network construction; end of it is an igraph file.
```{r}
#cor fucntion to generate all potential correlations between OTUs
coc<- rcorr(as.matrix(data), type=c("spearman")) 
cocr<-as.data.frame(coc$r)
cocp<-as.data.frame(coc$P)

subcoc<-list()
nom<-as.vector(colnames(cocr))
for(i in 1:ncol(cocr)){
  subcoc[[i]] <- subset(cocr, cocr[,i] > 0.6 | cocr[,i] < -0.6& cocp[,i] < 0.01, select = c(nom[[i]]))
} #this will generate a list of as many elements as OTUs, each element contains a vector with only OTU correlations above the predetermined cutoff (r=0.6 and p-value 0.5 here)

subcoc2<- matrix(0,ncol=3,nrow=0)
subcoc2<-data.frame(subcoc2)
colnames(subcoc2) <- c("sp1", "cor","sp2")
for(i in 1:length(subcoc)){
  temp<-as.data.frame(subcoc[[i]])
  temp<- setDT(temp, keep.rownames = TRUE)[]
  v <- rep(colnames(temp[,2]), nrow(temp))  
  temp<- mutate(temp, dr = v)
  colnames(temp) <- c("sp1", "cor","sp2")
subcoc2<-rbind(subcoc2,temp)
remove(temp)
} #resulting dataset contains edge information for network

links<-subcoc2[,c("sp2","sp1","cor")]
colnames(links)<-c("from", "to","weight")
nodes <-as.data.frame(unique(subcoc2[,3]))
colnames(nodes)<-c("id") #final edits to node and edge datasets
nodes<-merge(nodes,attributes,by = c("id"))

nrow(nodes); length(unique(nodes$id))
nrow(links); nrow(unique(links[,c("from", "to")]))
```
```{r}
att <-read.table("clipboard", header = T, sep = "\t")
link2<-merge(links,att,by = c("from"))
```
```{r}
att <-read.table("clipboard", header = T, sep = "\t")
link2<-merge(link2,att,by = c("to"))
write.csv(link2,file = "C:/Users/admin/Dropbox/b_manuscritpts/biofilmMARC/Datasets/from Gephi software/neg_vs_pos/Swan.csv")
```

```{r}
data <-read.table("clipboard", header = T, sep = "\t")
d <- density(data$x,bw=0.1) # returns the density data
plot(d)
```


